'use client';

import { useUser } from '@/firebase';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import Loading from '@/app/loading';
import { Film } from 'lucide-react';

const videos = [
  { id: 1, title: "Module 1: The Threat Landscape", src: "/video.mp4" },
  { id: 2, title: "Module 2: Protecting Your Digital Identity", src: "/2.mp4" },
  { id: 3, title: "Module 3: Safe Browsing & Email", src: "/3.mp4" },
  { id: 4, title: "Module 4: Device & Network Security", src: "/4.mp4" },
];

// A client-side component to handle fetching the video as a blob and creating a local URL.
// This makes it harder for simple tools to find the direct video source link.
function SecuredVideoPlayer({ src }: { src: string }) {
  const [videoUrl, setVideoUrl] = useState('');

  useEffect(() => {
    let objectUrl: string | null = null;

    const fetchVideo = async () => {
      try {
        const response = await fetch(src);
        if (!response.ok) {
          throw new Error('Video not found');
        }
        const blob = await response.blob();
        objectUrl = URL.createObjectURL(blob);
        setVideoUrl(objectUrl);
      } catch (error) {
        console.error("Failed to load video:", error);
        // Handle video loading error if needed
      }
    };

    fetchVideo();

    // Cleanup function to revoke the object URL when the component unmounts
    return () => {
      if (objectUrl) {
        URL.revokeObjectURL(objectUrl);
      }
    };
  }, [src]);

  if (!videoUrl) {
    return (
      <div className="w-full h-full bg-black flex items-center justify-center text-muted-foreground">
        Loading Secure Video...
      </div>
    );
  }

  return (
    <video controls className="h-full w-full" controlsList="nodownload">
      <source src={videoUrl} type="video/mp4" />
      Your browser does not support the video tag.
    </video>
  );
}


export default function VideoVaultPage() {
  const { user, isUserLoading } = useUser();
  const router = useRouter();

  // This logic is now handled by OnboardingGuard, but we keep it as a fallback.
  useEffect(() => {
    if (!isUserLoading && !user) {
      router.replace('/login');
    }
  }, [user, isUserLoading, router]);

  if (isUserLoading || !user) {
    return <Loading />;
  }

  return (
    <div className="container py-12 md:py-16">
      <div className="mb-10 text-center">
        <h1 className="font-headline text-4xl font-bold">High-Security Video Vault</h1>
        <p className="mt-2 text-muted-foreground">
          Your exclusive access to our secure video content.
        </p>
      </div>

      <div className="rounded-lg border bg-card p-4 md:p-6">
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2">
          {videos.map((video) => (
            <div key={video.id} className="overflow-hidden rounded-lg border bg-background shadow-lg">
                <div className="aspect-video bg-black">
                    <SecuredVideoPlayer src={video.src} />
                </div>
                <div className="p-4">
                    <h3 className="font-headline text-lg font-semibold flex items-center gap-2">
                        <Film className="h-5 w-5 text-primary" />
                        {video.title}
                    </h3>
                </div>
            </div>
          ))}
        </div>
      </div>
      
      <div className="mt-8 rounded-md border border-amber-500/50 bg-amber-500/10 p-4 text-sm text-amber-300">
        <h4 className="font-bold text-amber-200">Important Security Note</h4>
        <p className="mt-2">
          For enhanced security, these videos are currently loaded from the project's public directory. To fully protect this content from unauthorized access and tools like Burp Suite, the video files should be moved to a private Firebase Storage bucket. Access should be granted via short-lived, signed URLs generated by a backend Cloud Function that is protected with Firebase App Check. This setup ensures that only authenticated and verified app instances can request and stream video content.
        </p>
      </div>
    </div>
  );
}
